import { Card } from "@/components/ui/card"
import { StatusBadge } from "@/components/ui/status-badge"
import {
  agreements,
  clients,
  generatedReports,
  payments,
  plots,
  reservations,
} from "@/data/mock"

const reportTypes = [
  "Plot Occupancy",
  "Reservations",
  "Clients",
  "Payments",
  "Agreements",
  "Information Checking",
]

export function ReportsPage() {
  return (
    <div className="space-y-4">
      <Card title="Report Dashboard">
        <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">
          {[
            ["Total Plots", plots.length],
            ["Available", plots.filter((p) => p.status === "Available").length],
            ["Reserved", plots.filter((p) => p.status === "Reserved").length],
            ["Occupied", plots.filter((p) => p.status === "Occupied").length],
            ["Clients", clients.length],
            ["Reservations", reservations.length],
            ["Payments", payments.length],
            ["Agreements", agreements.length],
          ].map(([label, value]) => (
            <div key={label as string}>
              <p className="text-xs text-deep uppercase">{label}</p>
              <p className="text-xl font-bold">{value}</p>
            </div>
          ))}
        </div>
      </Card>

      <Card title="Generate Report">
        <div className="flex flex-wrap items-center gap-3">
          <select className="rounded-lg border border-deep/30 bg-cream px-3 py-1.5 text-sm">
            {reportTypes.map((t) => (
              <option key={t}>{t}</option>
            ))}
          </select>
          <select className="rounded-lg border border-deep/30 bg-cream px-3 py-1.5 text-sm">
            <option>All Cemeteries</option>
            <option>Mt. Zion Memorial Park</option>
            <option>Eternal Garden</option>
            <option>Batangas Floral Garden</option>
            <option>Batangas Public Cemetery</option>
          </select>
          <button className="neu-button px-4 py-1.5 text-sm">
            Generate
          </button>
        </div>
      </Card>

      <Card title="Recent Reports">
        <div className="overflow-x-auto"><table className="w-full text-sm">
          <thead>
            <tr className="text-left text-xs text-deep uppercase">
              <th>Report Name</th>
              <th>Type</th>
              <th>Date Generated</th>
              <th>Generated By</th>
              <th>Status</th>
              <th />
            </tr>
          </thead>
          <tbody>
            {generatedReports.map((r) => (
              <tr key={r.id} className="border-t border-deep/10">
                <td className="py-1.5">{r.name}</td>
                <td>{r.type}</td>
                <td>{r.dateGenerated}</td>
                <td>{r.generatedBy}</td>
                <td>
                  <StatusBadge status={r.status} />
                </td>
                <td>
                  <button className="neu-button px-2.5 py-1 text-[11px]">View</button>{" "}
                  <button className="neu-button px-2.5 py-1 text-[11px]">
                    Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table></div>
      </Card>
    </div>
  )
}
